export { default as Dashboard } from './Dashboard';
export { default as ErrorPage } from './ErrorPage';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Settings } from './Settings';
export { default as Profile } from './Profile';
export { default as Followers } from './Followers';
export { default as Following } from './Following';
export { default as Search } from './Search';
