import { db } from '../config/firebase-config';
import { collection, addDoc } from 'firebase/firestore';

const ingredients: string[] = [
    'flour',
    'sugar',
    'salt',
    'pepper',
    'olive oil',
    'garlic',
    'onion',
    'tomatoes',
    'potatoes',
    'carrots',
    'celery',
    'broccoli',
    'cauliflower',
    'spinach',
    'lettuce',
    'cucumber',
    'bell peppers',
    'jalapeño peppers',
    'habanero peppers',
    'ginger',
    'turmeric',
    'cumin',
    'coriander',
    'paprika',
    'cinnamon',
    'nutmeg',
    'cardamom',
    'cloves',
    'vanilla extract',
    'lemon juice',
    'lime juice',
    'apple cider vinegar',
    'balsamic vinegar',
    'soy sauce',
    'worcestershire sauce',
    'ketchup',
    'mustard',
    'mayonnaise',
    'sour cream',
    'cream cheese',
    'cheddar cheese',
    'mozzarella cheese',
    'parmesan cheese',
    'feta cheese',
    'blue cheese',
    'ricotta cheese',
    'cottage cheese',
    'milk',
    'butter',
    'cream',
    'yogurt',
    'eggs',
    'chicken',
    'beef',
    'pork',
    'lamb',
    'fish',
    'shrimp',
    'crab',
    'lobster',
    'clams',
    'mussels',
    'squid',
    'octopus',
    'tofu',
    'tempeh',
    'seitan',
    'lentils',
    'chickpeas',
    'kidney beans',
    'black beans',
    'white beans',
    'lima beans',
    'green beans',
    'peas',
    'corn',
    'rice',
    'quinoa',
    'bulgur',
    'couscous',
    'pasta',
    'bread',
    'bagels',
    'croissants',
    'muffins',
    'pancake mix',
    'waffles',
    'cereal',
    'oats',
    'granola',
    'almonds',
    'walnuts',
    'pecans',
    'cashews',
    'peanuts',
    'pistachios',
    'chia seeds',
    'flax seeds',
    'pumpkin seeds',
    'sesame seeds',
    'sunflower seeds',
    'raisins',
    'cranberries',
    'apricots',
    'dates',
    'figs',
    'apples',
    'bananas',
    'oranges',
    'kiwi',
    'mango',
    'pineapple',
    'strawberries',
    'blueberries',
    'raspberries',
    'blackberries',
    'watermelon',
    'cantaloupe',
    'honeydew',
    'grapes',
    'avocado',
    'cabbage',
    'brussels sprouts',
    'asparagus',
    'zucchini',
    'squash',
    'eggplant',
    'mushrooms',
    'artichokes',
    'okra',
    'leeks',
    'scallions',
    'shallots',
    'chocolate',
    'pudding',
    'cocoa powder',
    'chorizo',
    'ham',
    'bacon',
    'jam',
    'jelly',
];

export function createIngredientsCollection() {
    const ingredientsRef = collection(db, 'ingredients');
    ingredients.forEach(async (ingredient: string) => {
        const docRef = await addDoc(ingredientsRef, { name: ingredient });
        console.log('Document written with ID: ', docRef.id);
    });
}
